spring.application.name=EksamensProjektBilabonnement

# DB connection
spring.datasource.url = jdbc:mysql://localhost:3306/kailua_carrental
spring.datasource.username = root
spring.datasource.password = *




